# Generated by Django 5.2.4 on 2025-08-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appointment_feedback_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('cleaning', 'Dental Cleaning'), ('root_canal', 'Root Canal'), ('braces', 'Braces'), ('whitening', 'Teeth Whitening'), ('checkup', 'General Checkup')], max_length=50),
        ),
    ]
