# Generated by Django 5.2.4 on 2025-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_appointment_paid_appointment_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('cleaning', 'Teeth Cleaning'), ('teeth_whitening', 'Teeth Whitening'), ('teeth_polishing', 'Teeth Polishing'), ('teeth_filling', 'Teeth Filling'), ('extraction', 'Tooth Extraction'), ('dental_implants', 'Dental Implants'), ('crown_and_bridge', 'Crown and Bridge'), ('complete_denture', 'Complete Denture'), ('orthodontics', 'Orthodontics'), ('root_canal_treatment', 'Root Canal Treatment(RCT)')], max_length=50),
        ),
    ]
