# Generated by Django 5.2.4 on 2025-09-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, choices=[('cleaning', 'Teeth Cleaning'), ('teeth_whitening', 'Teeth Whitening'), ('teeth_polishing', 'Teeth Polishing'), ('teeth_filling', 'Teeth Filling'), ('extraction', 'Tooth Extraction'), ('dental_implants', 'Dental Implants'), ('crown_and_bridge', 'Crown and Bridge'), ('complete_denture', 'Complete Denture'), ('orthodontics', 'Orthodontics'), ('root_canal_treatment', 'Root Canal Treatment(RCT)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=122),
        ),
    ]
